// <auto-generated />
using System;
using CoreConsoleApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreConsoleApp.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20211012092849_MatremonialStatus_to_FK2")]
    partial class MatremonialStatus_to_FK2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreConsoleApp.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("CoreConsoleApp.MatrimonialStatusEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MatrimonialStatusEntry");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Single!"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Married!"
                        });
                });

            modelBuilder.Entity("CoreConsoleApp.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("MatrimonialStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("MatrimonialStatusId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("CoreConsoleApp.Zamorochka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Zamorochka");
                });

            modelBuilder.Entity("CoreConsoleApp.Person", b =>
                {
                    b.HasOne("CoreConsoleApp.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId");

                    b.HasOne("CoreConsoleApp.MatrimonialStatusEntry", "MatrimonialStatusEntry")
                        .WithMany()
                        .HasForeignKey("MatrimonialStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("MatrimonialStatusEntry");
                });

            modelBuilder.Entity("CoreConsoleApp.Zamorochka", b =>
                {
                    b.HasOne("CoreConsoleApp.Person", null)
                        .WithMany("Zamorochkas")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("CoreConsoleApp.Person", b =>
                {
                    b.Navigation("Zamorochkas");
                });
#pragma warning restore 612, 618
        }
    }
}
